# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-04-07 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='port',
            name='title',
            field=models.CharField(blank=True, max_length=70),
        ),
    ]
