# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-04-09 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_port_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='port',
            name='title',
            field=models.CharField(max_length=70),
        ),
    ]
