# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-11 09:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180409_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='port',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
